## <b>Created mainly for the purpose of the Capstone Project.</b>

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
print("Hello Capstone Project Course!")

Hello Capstone Project Course!


In [6]:
two_d = np.array([(1,2,3),(4,5,6)])
two_d

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
two_d.ndim

2

In [9]:
three_d = np.array([(1,2,3),(4,5,6),(7,8,9)],dtype= complex)
three_d

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

In [12]:
four_d = np.array([(1,2,3),(4,5,6),(7,8,9),(89,80,97)],dtype= complex)
four_d

array([[ 1.+0.j,  2.+0.j,  3.+0.j],
       [ 4.+0.j,  5.+0.j,  6.+0.j],
       [ 7.+0.j,  8.+0.j,  9.+0.j],
       [89.+0.j, 80.+0.j, 97.+0.j]])